SD. ДЗ 01, Васильев Роман
nizshee/software-design-au pull request #1
Opened 2016-09-20 16:55 UTC by nizshee

Первое задание по дизайну.

2016-10-11 13:37 UTC, yurii-litvinov requested changes
- $x=1
  $echo '$x'
  не работает
- $x=echo
  $$x 1
  тоже не работает, а, наверное, хотелось бы (хотя и не обязательно)
- Нужно ещё диаграмму классов и короткий текст с описанием архитектуры.

2016-10-11 13:37 UTC, yurii-litvinov commented on src/main/scala/com/github/nizshee/Bash.scala
> +/** Class that parse and execute sequence of parameters.
"parses and executes", а то как-то не по-английски

2016-10-11 13:37 UTC, yurii-litvinov commented on src/main/scala/com/github/nizshee/Bash.scala
> +  * @param parser the parser that will be use for parse
Тут тоже, "used"

2016-10-11 13:37 UTC, yurii-litvinov commented on src/main/scala/com/github/nizshee/argument/Argument.scala
> +    * @return string
Не очень информативно :)

2016-10-11 13:37 UTC, yurii-litvinov commented on src/main/scala/com/github/nizshee/program/Cat.scala
> +class Cat extends Program {
Командам тоже неплохо бы комментарий.

2016-10-11 13:37 UTC, yurii-litvinov commented on src/main/scala/com/github/nizshee/program/Wc.scala
> +    Stream(input.size.toString)
Хотелось, чтобы оно, как настоящий wc, возвращало количество букв, слов и строк. Но для архитектуры это не важно, так что можно и так.

2016-10-23 11:08 UTC, nizshee commented
Я поправил парсер, чтобы он учитывал $.
Поменял комментарии, добавил схему и описание.

2016-11-22 21:25 UTC, yurii-litvinov approved these changes

2016-11-22 21:25 UTC, merged