SD. ДЗ 02, Васильев Роман
nizshee/software-design-au pull request #2
Opened 2016-09-20 19:55 UTC by nizshee

2016-10-11 13:51 UTC, yurii-litvinov requested changes
- "-w" не работает
- Неплохо бы на него тест
- Надо больше комментариев

2016-10-26 10:28 UTC, nizshee commented
Добавил логику -w и тесты.
Добавил комментарии.

2016-11-22 21:49 UTC, yurii-litvinov commented
Мне кажется, грамматика "-w" не одобряет:
```
$grep -w scala build.sbt
`|' expected but `-' found
```

2016-11-26 14:05 UTC, nizshee commented
Моя ошибка. Там я парсинг строится на регулярных выражениях. 
В файле CombinatorParser есть переменная validTokens и в ней валидные конструкции которые могут встречаться в термах. 
Если какого то символа будет очень не хватать, то можно туда добавить...

2016-12-04 20:45 UTC, yurii-litvinov approved these changes

2016-12-04 20:46 UTC, merged